### ISSUE TITLE
Support for newer PHP versions

### ISSUE THREAD

**Issue by briedis** [laruence/taint#18]
Any hopes for support on newer php versions, like 5.5, 5.6? This is an awesome extension, but we really can't use it on our up-to-date server :(

**Comment by laruence** [comment]
Hey,  I won't be able to do a PHP-5.6 version release.. I am plan to make a new release after PHP7 is released. things could become simple with the zend_string type...

thanks

**Comment by briedis** [comment]
Thanks for your response! I understad. Hope it won't be too long for php7 :)

Thanks and goog luck!

**Comment by laruence** [comment]
php7 support is done, please checkout the php7 branch
