### ISSUE TITLE
function.echo

### ISSUE THREAD

**Issue by mickeyouyou** [laruence/taint#19]
鸟哥  `echo` 官网都说不是一个函数而是一个语言结构，为什么还要在输出的信息中表示这是一个function呢？

>echo 不是一个函数（它是一个语言结构）

首页的介绍中提到的echo ：
>Warning: main() [function.echo]: Attempt to echo a string that might be tainted

**Comment by laruence** [comment]
恩... echo不是function, 不过这个不是什么大问题, 只是为了错误信息统一才这么弄的. 下个版本修正下.

**Comment by mickeyouyou** [comment]
:+1:

**Comment by laruence** [comment]
php7的版本中已经不在显示function了
