### ISSUE TITLE
The php7 branch fails with VC14 x86 NTS

### ISSUE THREAD

**Issue by Jan-E** [laruence/taint#24]
@laruence 

	C:\php-sdk\php70dev>nmake php_taint.dll
	
	Microsoft (R) Program Maintenance Utility Version 14.00.23026.0
	Copyright (C) Microsoft Corporation.  All rights reserved.
	
	        "cl.exe" /D COMPILE_DL_TAINT /D TAINT_EXPORTS=1 /nologo /I . /I main /I Zend /I TSR
	M /I ext /D _WINDOWS /D ZEND_WIN32=1 /D PHP_WIN32=1 /D WIN32 /D _MBCS /W3 /FD /wd4996 /D_US
	E_32BIT_TIME_T=1 /guard:cf /MP /Zi /LD /MD /W3 /Ox /D NDebug /D NDEBUG /D ZEND_WIN32_FORCE_
	INLINE /GF /D ZEND_DEBUG=0 /I "C:\php-sdk\win32build\include" /D FD_SETSIZE=256 /I "..\zlib
	" /FoC:\php-sdk\php70dev\Release\ext\taint\ /FpC:\php-sdk\php70dev\Release\ext\taint\ /FRC:
	\php-sdk\php70dev\Release\ext\taint\ /FdC:\php-sdk\php70dev\Release\ext\taint\ /c ext\taint
	\taint.c
	taint.c
	ext\taint\taint.c(289): warning C4018: '<=': signed/unsigned mismatch
	ext\taint\taint.c(299): warning C4018: '<=': signed/unsigned mismatch
	ext\taint\taint.c(801): error C2440: 'function': cannot convert from 'int (__cdecl *)(zval
	*,zval *,zval *)' to 'binary_op_type'
	ext\taint\taint.c(801): warning C4024: 'php_taint_assign_op_overloaded_property': different
	 types for formal and actual parameter 5
	ext\taint\taint.c(842): error C2440: 'function': cannot convert from 'int (__cdecl *)(zval
	*,zval *,zval *)' to 'binary_op_type'
	ext\taint\taint.c(842): warning C4024: 'php_taint_binary_assign_op_obj_dim': different type
	s for formal and actual parameter 5
	ext\taint\taint.c(915): error C2440: 'function': cannot convert from 'int (__vectorcall *)(
	zval *,zval *,zval *)' to 'int (__cdecl *)(zval *,zval *,zval *)'
	ext\taint\taint.c(915): warning C4024: 'php_taint_binary_assign_op_helper': different types
	 for formal and actual parameter 1
	ext\taint\taint.c(917): error C2440: 'function': cannot convert from 'int (__vectorcall *)(
	zval *,zval *,zval *)' to 'int (__cdecl *)(zval *,zval *,zval *)'
	ext\taint\taint.c(917): warning C4024: 'php_taint_binary_assign_op_dim_helper': different t
	ypes for formal and actual parameter 1
	ext\taint\taint.c(919): error C2440: 'function': cannot convert from 'int (__vectorcall *)(
	zval *,zval *,zval *)' to 'int (__cdecl *)(zval *,zval *,zval *)'
	ext\taint\taint.c(919): warning C4024: 'php_taint_binary_assign_op_obj_helper': different t
	ypes for formal and actual parameter 1
	ext\taint\taint.c(970): warning C4018: '<': signed/unsigned mismatch
	NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\cl.
	exe"' : return code '0x2'
	Stop.

**Comment by laruence** [comment]
should be fixed now.. thanks for the reporting :)

**Comment by Jan-E** [comment]
OK. Tested with VC14 x64 TS (and PHP7 RC4). Fixed.
