### ISSUE TITLE
taint对PDO的检测是不起作用的

### ISSUE THREAD

**Issue by longlong2010** [laruence/taint#26]
taint中对PDO的检测并不起作用，发现原因是PHP中PDO的类名是大写的PDO，在进行类的判断时使用了小写的pdo，导致判断不起作用。另外mysqli中缺少对prepare语句的判断，虽大大部分情况是没有问题的，但如果个别参数还是用了嵌入的方式还是存在问题。希望下个版本中能够修复这个问题，谢谢！

**Comment by laruence** [comment]
嗯， PDO的类名是大写的， 已经提交了一个修复
