### ISSUE TITLE
字符串连接后无法触发taint

### ISSUE THREAD

**Issue by dreamans** [laruence/taint#29]
发现了一个问题，像这样调用时不会触发taint：
```
$var = $_GET['var'];
$var1 = $var . 'string';
echo $var1;
```
不知能否解决。

**Comment by laruence** [comment]
PHP7的版本？

**Comment by dreamans** [comment]
PHP5.4

**Comment by laruence** [comment]
恩......简单的建议是换PHP7吧....-_#... 实在不好意思, 因为这个扩展对内部实现依赖很重, 所以实在没有精力维护多个版本, PHP7是未来的主要维护版本

**Comment by dreamans** [comment]
感谢鸟哥的回复，我们产品线使用的是ODP框架，升级到PHP7成本太高了 :smile:
