### ISSUE TITLE
Do Taint  not support  php5.6?

### ISSUE THREAD

**Issue by stuven1989** [laruence/taint#38]
My testing environment: php5.6 + mysql + nginx.   I constructed the "EasyTalk" website in it and added taint extension to php, it is invalid that I request the web page.  The problem is in php_taint_send_var_handler and php_taint_assign_handle function.
@laruence

**Comment by laruence** [comment]
taint dosen't support 5.6 and is not going to support it due to complicated. 

however taint supports PHP 7+ well.

sorry &  thanks

**Comment by stuven1989** [comment]
I want to support php5.6,  Can you give me some  suggestion? I found that the major compatible reason is variable tracing caused. @laruence
