### ISSUE TITLE
doesnt work with xdebug enabled

### ISSUE THREAD

**Issue by staabm** [laruence/taint#47]
I am running php7.0.14 on ubuntu 14 and taint doesnt output any warnings when xdebug is loaded at the same time.

disabling the xdebug extension results into warnings beeing printed.

I am testing with the very simple example from the readme.

**Comment by staabm** [comment]
@derickr any insights whether this behaviour might depend on a certain xdebug setting and could be worked arround somehow?

**Comment by laruence** [comment]
yeah, they are conflict.... and actually, there should be a warning since taint already declare conflicts with xdebug

**Comment by laruence** [comment]
the reason is both xdebug and taint will override some user opcode handler

**Comment by staabm** [comment]
I didnt saw any error/warning.. did some guesswork which extension might be a problem and found xdebug "to be the cause"

**Comment by derickr** [comment]
It's not a setting. PHP doesn't allow two extensions to override the same user opcode handlers. Perhaps you can change the order of loading extensions, but that will likely break some Xdebug functionality.
