### ISSUE TITLE
conflict with xdebug?

### ISSUE THREAD

**Issue by joostfaassen** [laruence/taint#5]
Hi Laurence,

This is an awesome extension, thanks so much for developing this!

I detected a conflict between xdebug and php-taint, and developed a little test-case:

```php
$a = $_GET['test'];

$b = " " . $a; // this is where $b loses it's taint with xdebug

if (is_tainted($b)) {
  echo "without xdebug I go here"
} else {
  echo "with xdebug i go here";
}
```
I am not sure if this is a problem of xdebug or php-taint.

To avoid false-negatives, maybe php-taint can include a warning if it is running together with xdebug?

Keep up the great work!
Joost

**Comment by laruence** [comment]
sorry, both xdebug and taint set user opcode handlers, which can not be comptiable with each other.
