### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by remicollet** [laruence/taint#55]
For now build is refused (Unsupported PHP Version ID)

BTW using 7.1 code works (test suite passes)

```
-# elif PHP_VERSION_ID < 70200
+# elif PHP_VERSION_ID < 70300
```

Only 1 broken test because of "Deprecated: The each() function is deprecated."

What about allowing 7.2 ?

**Comment by Jan-E** [comment]
And that test was silenced by https://github.com/laruence/taint/commit/e41d11bb55aa16da57e152fecfce30a50b454c0d

@laruence Is there a reason not to allow 7.2?

**Comment by laruence** [comment]
7.2 is now supported in master, I am thinking maybe we should release it after 7.2's windows build is supported at pecl

**Comment by Jan-E** [comment]
Test results for PHP 7.2.0 beta1 x64 VC15 now:
```
=====================================================================
Number of tests :   24                24
Tests skipped   :    0 (  0.0%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    1 (  4.2%) (  4.2%)
Expected fail   :    0 (  0.0%) (  0.0%)
Tests passed    :   23 ( 95.8%) ( 95.8%)
---------------------------------------------------------------------
Time taken      :    1 seconds
=====================================================================

=====================================================================
FAILED TEST SUMMARY
---------------------------------------------------------------------
Check dirname, basename, pathinfo [N:\php-sdk\php70dev\ext\taint\tests\012.phpt]
=====================================================================
```
The fail has something to do with the %s, which is not defined on Windows::
```
TEST 12/24 [N:\php-sdk\php70dev\ext\taint\tests\012.phpt]
========DIFF========
003+ Warning: test() [echo]: Attempt to echo a string that might be tainted in N:\php-sdk\php70dev\ext\taint\tests\012.php on line 6
003- Warning: test() [echo]: Attempt to echo a string that might be tainted in %stests/012.php on line 6
007+ Warning: test() [echo]: Attempt to echo a string that might be tainted in N:\php-sdk\php70dev\ext\taint\tests\012.php on line 8
007- Warning: test() [echo]: Attempt to echo a string that might be tainted in %stests/012.php on line 8
========DONE========
FAIL Check dirname, basename, pathinfo [N:\php-sdk\php70dev\ext\taint\tests\012.phpt]
```

**Comment by Jan-E** [comment]
> I am thinking maybe we should release it after 7.2's windows build is supported at pecl

That should not be too hard. After all, the Windows builds already work fine on Appveyor. @weltling: when will you add the PHP 7.2 extensions on windows.php.net?

**Comment by laruence** [comment]
the test should be fixed

**Comment by weltling** [comment]
@Jan-E automated snapshot builds against 7.2 are in plan this month. Most recent releases will be then mass rebuilt after 7.2 GA and 7.2 will be then included into the regular build chain.

Thanks.

**Comment by Jan-E** [comment]
Confirmed. Would you be interested in a appveyor.yml to test the nts builds on Windows?

**Comment by Jan-E** [comment]
@laruence Appveyor:
https://ci.appveyor.com/project/Jan-E/taint/build/master.5/job/kbwk3nvrgt4ns77j#L592
https://ci.appveyor.com/project/Jan-E/taint/build/master.5/job/o6src8uu855memrf#L742

If you create a project for 'laruence/taint', I will create a PR for you.
