### ISSUE TITLE
taint-2.0.3不支持php.7.0.0

### ISSUE THREAD

**Issue by wxxiong6** [laruence/taint#59]
编译时报下面错误
./php_taint.h:60:3: error: "Unsupported PHP Version ID:" PHP_VERSION_ID
# error "Unsupported PHP Version ID:" PHP_VERSION_ID
我的php版本
`PHP 7.0.0 (cli) (built: Dec 10 2015 14:13:08) ( NTS )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.4.0RC4-dev, Copyright (c) 2002-2015, by Derick Rethans`

查看源码./php_taint.h:60:3有这么一段

`#if PHP_VERSION_ID > 70000`
`# if PHP_VERSION_ID >= 70200`
`#  undef IS_STR_TAINT_POSSIBLE`
   /* Coflicts with GC_COLLECTABLE which is introduced in 7.2 */
`#  define IS_STR_TAINT_POSSIBLE (1<<6)`
`# endif`
`#else`
`# error "Unsupported PHP Version ID:" PHP_VERSION_ID`
`#endif`

要支持php7.0.0，需要改成下面这样。
`#if PHP_VERSION_ID >= 70000`

**Comment by laruence** [comment]
你说的对! 已经修复, thanks :)

**Comment by Jan-E** [comment]
@laruence This only works if you replace every occurrence of
`#if PHP_7_0`
with
`#if PHP_VERSION_ID < 70100`

**Comment by Jan-E** [comment]
PHP_7_0 was removed in https://github.com/laruence/taint/commit/41a285ac6e81c534d54f5b8a752c870384e8c8b9#diff-74ab34a3d62d7eac229c89744ab05047
