### ISSUE TITLE
compatibility with PHP 5.3.3

### ISSUE THREAD

**Issue by christopherowen** [laruence/taint#6]
PHP version 5.3.3 is the version that ships with Redhat Enterprise Linux 6 and CentOS 6.

make test will return the following on these systems:

Warning: PHP Startup: Unable to load dynamic library '/usr/local/src/taint-1.2.2/modules/taint.so' - /usr/local/src/taint-1.2.2/modules/taint.so: undefined symbol: INIT_PZVAL_COPY in Unknown on line 0

and compared to a php 5.4 installation, INIT_PZVAL_COPY is truly not defined in /usr/include/php/Zend/zend.h.

Is there any way to get taint working with the php version shipped by RHEL/CentOS?

**Comment by jimmyyem** [comment]
I installed taint  and I download  source code from: http://pecl.php.net/package/taint. Then i restart http but I found the following error message from /tmp/php_error.log
--------------------------------------------------------------------------------------
[05-Jan-2015 16:54:08] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/taint.so' - /usr/lib64/php/modules/taint.so: undefined symbol: INIT_PZVAL_COPY in Unknown on line 0

**Comment by christopherowen** [comment]
the patch is still necessary
